/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BecomeAdminResponse {
  'isAlreadyAdmin' : boolean,
  'error' : [] | [string],
  'success' : boolean,
}
export interface BuildMetadata {
  'gitCommitHash' : string,
  'buildTime' : bigint,
  'canisterId' : Principal,
}
export interface BulkChallanCreateResult {
  'id' : string,
  'created' : [] | [Challan],
  'error' : [] | [string],
  'success' : boolean,
}
export interface Challan {
  'id' : string,
  'clientName' : string,
  'venue' : string,
  'site' : string,
  'numberOfDays' : number,
  'creationDate' : bigint,
  'freight' : number,
  'items' : Array<ChallanItem>,
  'rentDate' : bigint,
  'returned' : boolean,
}
export interface ChallanItem {
  'rate' : number,
  'rentalDays' : number,
  'itemName' : string,
  'quantity' : number,
}
export interface Client { 'name' : string, 'createdAt' : bigint }
export interface ClientBulkCreateResult {
  'created' : [] | [Client],
  'name' : string,
  'error' : [] | [string],
  'success' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface InventoryBulkCreateResult {
  'created' : [] | [InventoryItem],
  'name' : string,
  'error' : [] | [string],
  'success' : boolean,
}
export interface InventoryItem {
  'dailyRate' : number,
  'availableQuantity' : number,
  'name' : string,
  'issuedQuantity' : number,
  'totalQuantity' : number,
}
export interface Payment {
  'id' : string,
  'client' : string,
  'referenceNumber' : string,
  'date' : bigint,
  'mode' : string,
  'createdAt' : bigint,
  'site' : string,
  'amount' : number,
}
export interface PaymentBulkCreateResult {
  'id' : string,
  'created' : [] | [Payment],
  'error' : [] | [string],
  'success' : boolean,
}
export interface PettyCash {
  'categoryExpenses' : Array<PettyCashCategory>,
  'date' : bigint,
  'expenses' : number,
  'createdAt' : bigint,
  'transferFromCashEquivalents' : number,
  'staffAdvance' : number,
  'closingBalance' : number,
  'openingBalance' : number,
  'handoverToMd' : number,
  'cashFromMd' : number,
  'remarks' : string,
  'netChange' : number,
}
export interface PettyCashAttachment { 'id' : string, 'blob' : ExternalBlob }
export interface PettyCashBulkCreateResult {
  'created' : [] | [PettyCash],
  'date' : bigint,
  'error' : [] | [string],
  'success' : boolean,
}
export interface PettyCashCategory { 'title' : string, 'amount' : number }
export interface PettyCashWithAttachments {
  'attachments' : Array<PettyCashAttachment>,
  'pettyCash' : PettyCash,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAttachmentToPettyCashRecord' : ActorMethod<
    [bigint, PettyCashAttachment],
    Array<PettyCashAttachment>
  >,
  'addClient' : ActorMethod<[string, bigint], undefined>,
  'addInventoryItem' : ActorMethod<[string, number, number], undefined>,
  'addPayment' : ActorMethod<
    [string, bigint, string, string, number, string, bigint, string],
    undefined
  >,
  'addPettyCash' : ActorMethod<
    [
      bigint,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      Array<PettyCashCategory>,
      string,
      bigint,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'becomeBootstrapAdmin' : ActorMethod<[boolean], BecomeAdminResponse>,
  'bulkAddPayments' : ActorMethod<
    [Array<Payment>],
    Array<PaymentBulkCreateResult>
  >,
  'bulkAddPettyCash' : ActorMethod<
    [Array<PettyCash>],
    Array<PettyCashBulkCreateResult>
  >,
  'bulkCreateClients' : ActorMethod<
    [Array<Client>],
    Array<ClientBulkCreateResult>
  >,
  'bulkCreateInventoryItems' : ActorMethod<
    [Array<InventoryItem>],
    Array<InventoryBulkCreateResult>
  >,
  'clearPettyCashAttachments' : ActorMethod<[bigint], undefined>,
  'createBulkChallans' : ActorMethod<
    [Array<Challan>],
    Array<BulkChallanCreateResult>
  >,
  'createChallan' : ActorMethod<
    [
      string,
      string,
      string,
      Array<ChallanItem>,
      number,
      number,
      bigint,
      string,
      bigint,
    ],
    undefined
  >,
  'deleteChallan' : ActorMethod<[string], undefined>,
  'deleteClient' : ActorMethod<[string], undefined>,
  'deleteInventoryItem' : ActorMethod<[string], undefined>,
  'deletePettyCash' : ActorMethod<[bigint], undefined>,
  'getAllChallans' : ActorMethod<[], Array<Challan>>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllPettyCashRecords' : ActorMethod<[], Array<PettyCash>>,
  'getAllPettyCashRecordsWithAttachments' : ActorMethod<
    [],
    Array<PettyCashWithAttachments>
  >,
  'getAttachmentsForPettyCashRecord' : ActorMethod<
    [bigint],
    Array<PettyCashAttachment>
  >,
  'getBuildMetadata' : ActorMethod<[], BuildMetadata>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChallansByClient' : ActorMethod<[string], Array<Challan>>,
  'getChallansByDateRange' : ActorMethod<[bigint, bigint], Array<Challan>>,
  'getInventory' : ActorMethod<[], Array<InventoryItem>>,
  'getPaymentsByClient' : ActorMethod<[string], Array<Payment>>,
  'getPaymentsByDateRange' : ActorMethod<[bigint, bigint], Array<Payment>>,
  'getPettyCashByDateRange' : ActorMethod<[bigint, bigint], Array<PettyCash>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'healthCheck' : ActorMethod<[], bigint>,
  'isAdminOrBootstrapAdminExternal' : ActorMethod<[], boolean>,
  'isBootstrapAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markChallanReturned' : ActorMethod<[string], undefined>,
  'removeAttachmentFromPettyCashRecord' : ActorMethod<
    [bigint, string],
    Array<PettyCashAttachment>
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'revertChallanToActive' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateChallan' : ActorMethod<
    [
      string,
      string,
      string,
      Array<ChallanItem>,
      number,
      number,
      bigint,
      string,
    ],
    undefined
  >,
  /**
   * / Update rent date of all existing challans by re-uploading original csv file.
   * / This is an admin-only operation to restore corrupted rent dates.
   */
  'updateChallanRentDates' : ActorMethod<[Array<Challan>], undefined>,
  'updateInventoryItem' : ActorMethod<[string, number, number], undefined>,
  'updatePettyCash' : ActorMethod<
    [
      bigint,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      Array<PettyCashCategory>,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];