/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PettyCashAttachment = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
});
export const PettyCashCategory = IDL.Record({
  'title' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BecomeAdminResponse = IDL.Record({
  'isAlreadyAdmin' : IDL.Bool,
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const Payment = IDL.Record({
  'id' : IDL.Text,
  'client' : IDL.Text,
  'referenceNumber' : IDL.Text,
  'date' : IDL.Int,
  'mode' : IDL.Text,
  'createdAt' : IDL.Int,
  'site' : IDL.Text,
  'amount' : IDL.Float64,
});
export const PaymentBulkCreateResult = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Opt(Payment),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const PettyCash = IDL.Record({
  'categoryExpenses' : IDL.Vec(PettyCashCategory),
  'date' : IDL.Int,
  'expenses' : IDL.Float64,
  'createdAt' : IDL.Int,
  'transferFromCashEquivalents' : IDL.Float64,
  'staffAdvance' : IDL.Float64,
  'closingBalance' : IDL.Float64,
  'openingBalance' : IDL.Float64,
  'handoverToMd' : IDL.Float64,
  'cashFromMd' : IDL.Float64,
  'remarks' : IDL.Text,
  'netChange' : IDL.Float64,
});
export const PettyCashBulkCreateResult = IDL.Record({
  'created' : IDL.Opt(PettyCash),
  'date' : IDL.Int,
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const Client = IDL.Record({ 'name' : IDL.Text, 'createdAt' : IDL.Int });
export const ClientBulkCreateResult = IDL.Record({
  'created' : IDL.Opt(Client),
  'name' : IDL.Text,
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const InventoryItem = IDL.Record({
  'dailyRate' : IDL.Float64,
  'availableQuantity' : IDL.Float64,
  'name' : IDL.Text,
  'issuedQuantity' : IDL.Float64,
  'totalQuantity' : IDL.Float64,
});
export const InventoryBulkCreateResult = IDL.Record({
  'created' : IDL.Opt(InventoryItem),
  'name' : IDL.Text,
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const ChallanItem = IDL.Record({
  'rate' : IDL.Float64,
  'rentalDays' : IDL.Float64,
  'itemName' : IDL.Text,
  'quantity' : IDL.Float64,
});
export const Challan = IDL.Record({
  'id' : IDL.Text,
  'clientName' : IDL.Text,
  'venue' : IDL.Text,
  'site' : IDL.Text,
  'numberOfDays' : IDL.Float64,
  'creationDate' : IDL.Int,
  'freight' : IDL.Float64,
  'items' : IDL.Vec(ChallanItem),
  'rentDate' : IDL.Int,
  'returned' : IDL.Bool,
});
export const BulkChallanCreateResult = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Opt(Challan),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const PettyCashWithAttachments = IDL.Record({
  'attachments' : IDL.Vec(PettyCashAttachment),
  'pettyCash' : PettyCash,
});
export const BuildMetadata = IDL.Record({
  'gitCommitHash' : IDL.Text,
  'buildTime' : IDL.Int,
  'canisterId' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAttachmentToPettyCashRecord' : IDL.Func(
      [IDL.Int, PettyCashAttachment],
      [IDL.Vec(PettyCashAttachment)],
      [],
    ),
  'addClient' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'addInventoryItem' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
  'addPayment' : IDL.Func(
      [
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Int,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addPettyCash' : IDL.Func(
      [
        IDL.Int,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Vec(PettyCashCategory),
        IDL.Text,
        IDL.Int,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'becomeBootstrapAdmin' : IDL.Func([IDL.Bool], [BecomeAdminResponse], []),
  'bulkAddPayments' : IDL.Func(
      [IDL.Vec(Payment)],
      [IDL.Vec(PaymentBulkCreateResult)],
      [],
    ),
  'bulkAddPettyCash' : IDL.Func(
      [IDL.Vec(PettyCash)],
      [IDL.Vec(PettyCashBulkCreateResult)],
      [],
    ),
  'bulkCreateClients' : IDL.Func(
      [IDL.Vec(Client)],
      [IDL.Vec(ClientBulkCreateResult)],
      [],
    ),
  'bulkCreateInventoryItems' : IDL.Func(
      [IDL.Vec(InventoryItem)],
      [IDL.Vec(InventoryBulkCreateResult)],
      [],
    ),
  'clearPettyCashAttachments' : IDL.Func([IDL.Int], [], []),
  'createBulkChallans' : IDL.Func(
      [IDL.Vec(Challan)],
      [IDL.Vec(BulkChallanCreateResult)],
      [],
    ),
  'createChallan' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ChallanItem),
        IDL.Float64,
        IDL.Float64,
        IDL.Int,
        IDL.Text,
        IDL.Int,
      ],
      [],
      [],
    ),
  'deleteChallan' : IDL.Func([IDL.Text], [], []),
  'deleteClient' : IDL.Func([IDL.Text], [], []),
  'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
  'deletePettyCash' : IDL.Func([IDL.Int], [], []),
  'getAllChallans' : IDL.Func([], [IDL.Vec(Challan)], ['query']),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllPettyCashRecords' : IDL.Func([], [IDL.Vec(PettyCash)], ['query']),
  'getAllPettyCashRecordsWithAttachments' : IDL.Func(
      [],
      [IDL.Vec(PettyCashWithAttachments)],
      ['query'],
    ),
  'getAttachmentsForPettyCashRecord' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(PettyCashAttachment)],
      ['query'],
    ),
  'getBuildMetadata' : IDL.Func([], [BuildMetadata], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChallansByClient' : IDL.Func([IDL.Text], [IDL.Vec(Challan)], ['query']),
  'getChallansByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Challan)],
      ['query'],
    ),
  'getInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getPaymentsByClient' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
  'getPaymentsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getPettyCashByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(PettyCash)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'healthCheck' : IDL.Func([], [IDL.Int], ['query']),
  'isAdminOrBootstrapAdminExternal' : IDL.Func([], [IDL.Bool], ['query']),
  'isBootstrapAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'markChallanReturned' : IDL.Func([IDL.Text], [], []),
  'removeAttachmentFromPettyCashRecord' : IDL.Func(
      [IDL.Int, IDL.Text],
      [IDL.Vec(PettyCashAttachment)],
      [],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'revertChallanToActive' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateChallan' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ChallanItem),
        IDL.Float64,
        IDL.Float64,
        IDL.Int,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateChallanRentDates' : IDL.Func([IDL.Vec(Challan)], [], []),
  'updateInventoryItem' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'updatePettyCash' : IDL.Func(
      [
        IDL.Int,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Vec(PettyCashCategory),
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PettyCashAttachment = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
  });
  const PettyCashCategory = IDL.Record({
    'title' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BecomeAdminResponse = IDL.Record({
    'isAlreadyAdmin' : IDL.Bool,
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const Payment = IDL.Record({
    'id' : IDL.Text,
    'client' : IDL.Text,
    'referenceNumber' : IDL.Text,
    'date' : IDL.Int,
    'mode' : IDL.Text,
    'createdAt' : IDL.Int,
    'site' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const PaymentBulkCreateResult = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Opt(Payment),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const PettyCash = IDL.Record({
    'categoryExpenses' : IDL.Vec(PettyCashCategory),
    'date' : IDL.Int,
    'expenses' : IDL.Float64,
    'createdAt' : IDL.Int,
    'transferFromCashEquivalents' : IDL.Float64,
    'staffAdvance' : IDL.Float64,
    'closingBalance' : IDL.Float64,
    'openingBalance' : IDL.Float64,
    'handoverToMd' : IDL.Float64,
    'cashFromMd' : IDL.Float64,
    'remarks' : IDL.Text,
    'netChange' : IDL.Float64,
  });
  const PettyCashBulkCreateResult = IDL.Record({
    'created' : IDL.Opt(PettyCash),
    'date' : IDL.Int,
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const Client = IDL.Record({ 'name' : IDL.Text, 'createdAt' : IDL.Int });
  const ClientBulkCreateResult = IDL.Record({
    'created' : IDL.Opt(Client),
    'name' : IDL.Text,
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const InventoryItem = IDL.Record({
    'dailyRate' : IDL.Float64,
    'availableQuantity' : IDL.Float64,
    'name' : IDL.Text,
    'issuedQuantity' : IDL.Float64,
    'totalQuantity' : IDL.Float64,
  });
  const InventoryBulkCreateResult = IDL.Record({
    'created' : IDL.Opt(InventoryItem),
    'name' : IDL.Text,
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const ChallanItem = IDL.Record({
    'rate' : IDL.Float64,
    'rentalDays' : IDL.Float64,
    'itemName' : IDL.Text,
    'quantity' : IDL.Float64,
  });
  const Challan = IDL.Record({
    'id' : IDL.Text,
    'clientName' : IDL.Text,
    'venue' : IDL.Text,
    'site' : IDL.Text,
    'numberOfDays' : IDL.Float64,
    'creationDate' : IDL.Int,
    'freight' : IDL.Float64,
    'items' : IDL.Vec(ChallanItem),
    'rentDate' : IDL.Int,
    'returned' : IDL.Bool,
  });
  const BulkChallanCreateResult = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Opt(Challan),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const PettyCashWithAttachments = IDL.Record({
    'attachments' : IDL.Vec(PettyCashAttachment),
    'pettyCash' : PettyCash,
  });
  const BuildMetadata = IDL.Record({
    'gitCommitHash' : IDL.Text,
    'buildTime' : IDL.Int,
    'canisterId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAttachmentToPettyCashRecord' : IDL.Func(
        [IDL.Int, PettyCashAttachment],
        [IDL.Vec(PettyCashAttachment)],
        [],
      ),
    'addClient' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'addInventoryItem' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
    'addPayment' : IDL.Func(
        [
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Int,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addPettyCash' : IDL.Func(
        [
          IDL.Int,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Vec(PettyCashCategory),
          IDL.Text,
          IDL.Int,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'becomeBootstrapAdmin' : IDL.Func([IDL.Bool], [BecomeAdminResponse], []),
    'bulkAddPayments' : IDL.Func(
        [IDL.Vec(Payment)],
        [IDL.Vec(PaymentBulkCreateResult)],
        [],
      ),
    'bulkAddPettyCash' : IDL.Func(
        [IDL.Vec(PettyCash)],
        [IDL.Vec(PettyCashBulkCreateResult)],
        [],
      ),
    'bulkCreateClients' : IDL.Func(
        [IDL.Vec(Client)],
        [IDL.Vec(ClientBulkCreateResult)],
        [],
      ),
    'bulkCreateInventoryItems' : IDL.Func(
        [IDL.Vec(InventoryItem)],
        [IDL.Vec(InventoryBulkCreateResult)],
        [],
      ),
    'clearPettyCashAttachments' : IDL.Func([IDL.Int], [], []),
    'createBulkChallans' : IDL.Func(
        [IDL.Vec(Challan)],
        [IDL.Vec(BulkChallanCreateResult)],
        [],
      ),
    'createChallan' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ChallanItem),
          IDL.Float64,
          IDL.Float64,
          IDL.Int,
          IDL.Text,
          IDL.Int,
        ],
        [],
        [],
      ),
    'deleteChallan' : IDL.Func([IDL.Text], [], []),
    'deleteClient' : IDL.Func([IDL.Text], [], []),
    'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
    'deletePettyCash' : IDL.Func([IDL.Int], [], []),
    'getAllChallans' : IDL.Func([], [IDL.Vec(Challan)], ['query']),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllPettyCashRecords' : IDL.Func([], [IDL.Vec(PettyCash)], ['query']),
    'getAllPettyCashRecordsWithAttachments' : IDL.Func(
        [],
        [IDL.Vec(PettyCashWithAttachments)],
        ['query'],
      ),
    'getAttachmentsForPettyCashRecord' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(PettyCashAttachment)],
        ['query'],
      ),
    'getBuildMetadata' : IDL.Func([], [BuildMetadata], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChallansByClient' : IDL.Func([IDL.Text], [IDL.Vec(Challan)], ['query']),
    'getChallansByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Challan)],
        ['query'],
      ),
    'getInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getPaymentsByClient' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
    'getPaymentsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getPettyCashByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(PettyCash)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'healthCheck' : IDL.Func([], [IDL.Int], ['query']),
    'isAdminOrBootstrapAdminExternal' : IDL.Func([], [IDL.Bool], ['query']),
    'isBootstrapAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'markChallanReturned' : IDL.Func([IDL.Text], [], []),
    'removeAttachmentFromPettyCashRecord' : IDL.Func(
        [IDL.Int, IDL.Text],
        [IDL.Vec(PettyCashAttachment)],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'revertChallanToActive' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateChallan' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ChallanItem),
          IDL.Float64,
          IDL.Float64,
          IDL.Int,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateChallanRentDates' : IDL.Func([IDL.Vec(Challan)], [], []),
    'updateInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updatePettyCash' : IDL.Func(
        [
          IDL.Int,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Vec(PettyCashCategory),
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };