/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BecomeAdminResponse {
    isAlreadyAdmin: boolean;
    error?: string;
    success: boolean;
}
export interface PettyCashAttachment {
    id: string;
    blob: ExternalBlob;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PettyCashBulkCreateResult {
    created?: PettyCash;
    date: bigint;
    error?: string;
    success: boolean;
}
export interface ClientBulkCreateResult {
    created?: Client;
    name: string;
    error?: string;
    success: boolean;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PettyCash {
    categoryExpenses: Array<PettyCashCategory>;
    date: bigint;
    expenses: number;
    createdAt: bigint;
    transferFromCashEquivalents: number;
    staffAdvance: number;
    closingBalance: number;
    openingBalance: number;
    handoverToMd: number;
    cashFromMd: number;
    remarks: string;
    netChange: number;
}
export interface Payment {
    id: string;
    client: string;
    referenceNumber: string;
    date: bigint;
    mode: string;
    createdAt: bigint;
    site: string;
    amount: number;
}
export interface InventoryBulkCreateResult {
    created?: InventoryItem;
    name: string;
    error?: string;
    success: boolean;
}
export interface BuildMetadata {
    gitCommitHash: string;
    buildTime: bigint;
    canisterId: Principal;
}
export interface InventoryItem {
    dailyRate: number;
    availableQuantity: number;
    name: string;
    issuedQuantity: number;
    totalQuantity: number;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface PettyCashWithAttachments {
    attachments: Array<PettyCashAttachment>;
    pettyCash: PettyCash;
}
export interface PettyCashCategory {
    title: string;
    amount: number;
}
export interface Challan {
    id: string;
    clientName: string;
    venue: string;
    site: string;
    numberOfDays: number;
    creationDate: bigint;
    freight: number;
    items: Array<ChallanItem>;
    rentDate: bigint;
    returned: boolean;
}
export interface BulkChallanCreateResult {
    id: string;
    created?: Challan;
    error?: string;
    success: boolean;
}
export interface Client {
    name: string;
    createdAt: bigint;
}
export interface ChallanItem {
    rate: number;
    rentalDays: number;
    itemName: string;
    quantity: number;
}
export interface UserProfile {
    name: string;
}
export interface PaymentBulkCreateResult {
    id: string;
    created?: Payment;
    error?: string;
    success: boolean;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAttachmentToPettyCashRecord(date: bigint, attachment: PettyCashAttachment): Promise<Array<PettyCashAttachment>>;
    addClient(name: string, createdAt: bigint): Promise<void>;
    addInventoryItem(name: string, totalQuantity: number, dailyRate: number): Promise<void>;
    addPayment(id: string, date: bigint, client: string, mode: string, amount: number, referenceNumber: string, createdAt: bigint, site: string): Promise<void>;
    addPettyCash(date: bigint, openingBalance: number, cashFromMd: number, expenses: number, staffAdvance: number, handoverToMd: number, netChange: number, closingBalance: number, transferFromCashEquivalents: number, categoryExpenses: Array<PettyCashCategory>, remarks: string, createdAt: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    becomeBootstrapAdmin(isAdminDomain: boolean): Promise<BecomeAdminResponse>;
    bulkAddPayments(batch: Array<Payment>): Promise<Array<PaymentBulkCreateResult>>;
    bulkAddPettyCash(batch: Array<PettyCash>): Promise<Array<PettyCashBulkCreateResult>>;
    bulkCreateClients(batch: Array<Client>): Promise<Array<ClientBulkCreateResult>>;
    bulkCreateInventoryItems(batch: Array<InventoryItem>): Promise<Array<InventoryBulkCreateResult>>;
    clearPettyCashAttachments(date: bigint): Promise<void>;
    createBulkChallans(batch: Array<Challan>): Promise<Array<BulkChallanCreateResult>>;
    createChallan(id: string, clientName: string, venue: string, items: Array<ChallanItem>, freight: number, numberOfDays: number, rentDate: bigint, site: string, creationDate: bigint): Promise<void>;
    deleteChallan(id: string): Promise<void>;
    deleteClient(name: string): Promise<void>;
    deleteInventoryItem(name: string): Promise<void>;
    deletePettyCash(date: bigint): Promise<void>;
    getAllChallans(): Promise<Array<Challan>>;
    getAllClients(): Promise<Array<Client>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllPettyCashRecords(): Promise<Array<PettyCash>>;
    getAllPettyCashRecordsWithAttachments(): Promise<Array<PettyCashWithAttachments>>;
    getAttachmentsForPettyCashRecord(date: bigint): Promise<Array<PettyCashAttachment>>;
    getBuildMetadata(): Promise<BuildMetadata>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChallansByClient(client: string): Promise<Array<Challan>>;
    getChallansByDateRange(startDate: bigint, endDate: bigint): Promise<Array<Challan>>;
    getInventory(): Promise<Array<InventoryItem>>;
    getPaymentsByClient(client: string): Promise<Array<Payment>>;
    getPaymentsByDateRange(startDate: bigint, endDate: bigint): Promise<Array<Payment>>;
    getPettyCashByDateRange(startDate: bigint, endDate: bigint): Promise<Array<PettyCash>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    healthCheck(): Promise<bigint>;
    isAdminOrBootstrapAdminExternal(): Promise<boolean>;
    isBootstrapAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    markChallanReturned(id: string): Promise<void>;
    removeAttachmentFromPettyCashRecord(date: bigint, attachmentId: string): Promise<Array<PettyCashAttachment>>;
    requestApproval(): Promise<void>;
    revertChallanToActive(_id: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateChallan(id: string, clientName: string, venue: string, items: Array<ChallanItem>, freight: number, numberOfDays: number, rentDate: bigint, site: string): Promise<void>;
    /**
     * / Update rent date of all existing challans by re-uploading original csv file.
     * / This is an admin-only operation to restore corrupted rent dates.
     */
    updateChallanRentDates(challanData: Array<Challan>): Promise<void>;
    updateInventoryItem(name: string, totalQuantity: number, dailyRate: number): Promise<void>;
    updatePettyCash(originalDate: bigint, openingBalance: number, cashFromMd: number, expenses: number, staffAdvance: number, handoverToMd: number, netChange: number, closingBalance: number, transferFromCashEquivalents: number, categoryExpenses: Array<PettyCashCategory>, remarks: string): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, BecomeAdminResponse as _BecomeAdminResponse, BulkChallanCreateResult as _BulkChallanCreateResult, Challan as _Challan, Client as _Client, ClientBulkCreateResult as _ClientBulkCreateResult, ExternalBlob as _ExternalBlob, InventoryBulkCreateResult as _InventoryBulkCreateResult, InventoryItem as _InventoryItem, Payment as _Payment, PaymentBulkCreateResult as _PaymentBulkCreateResult, PettyCash as _PettyCash, PettyCashAttachment as _PettyCashAttachment, PettyCashBulkCreateResult as _PettyCashBulkCreateResult, PettyCashWithAttachments as _PettyCashWithAttachments, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAttachmentToPettyCashRecord(arg0: bigint, arg1: PettyCashAttachment): Promise<Array<PettyCashAttachment>> {
        if (this.processError) {
            try {
                const result = await this.actor.addAttachmentToPettyCashRecord(arg0, await to_candid_PettyCashAttachment_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAttachmentToPettyCashRecord(arg0, await to_candid_PettyCashAttachment_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async addClient(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addClient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClient(arg0, arg1);
            return result;
        }
    }
    async addInventoryItem(arg0: string, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryItem(arg0, arg1, arg2);
            return result;
        }
    }
    async addPayment(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: number, arg5: string, arg6: bigint, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addPettyCash(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Array<PettyCashCategory>, arg10: string, arg11: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPettyCash(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPettyCash(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async becomeBootstrapAdmin(arg0: boolean): Promise<BecomeAdminResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.becomeBootstrapAdmin(arg0);
                return from_candid_BecomeAdminResponse_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.becomeBootstrapAdmin(arg0);
            return from_candid_BecomeAdminResponse_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async bulkAddPayments(arg0: Array<Payment>): Promise<Array<PaymentBulkCreateResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAddPayments(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAddPayments(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async bulkAddPettyCash(arg0: Array<PettyCash>): Promise<Array<PettyCashBulkCreateResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAddPettyCash(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAddPettyCash(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async bulkCreateClients(arg0: Array<Client>): Promise<Array<ClientBulkCreateResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkCreateClients(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkCreateClients(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async bulkCreateInventoryItems(arg0: Array<InventoryItem>): Promise<Array<InventoryBulkCreateResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkCreateInventoryItems(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkCreateInventoryItems(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearPettyCashAttachments(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearPettyCashAttachments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearPettyCashAttachments(arg0);
            return result;
        }
    }
    async createBulkChallans(arg0: Array<Challan>): Promise<Array<BulkChallanCreateResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.createBulkChallans(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBulkChallans(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async createChallan(arg0: string, arg1: string, arg2: string, arg3: Array<ChallanItem>, arg4: number, arg5: number, arg6: bigint, arg7: string, arg8: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createChallan(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChallan(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async deleteChallan(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChallan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChallan(arg0);
            return result;
        }
    }
    async deleteClient(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteInventoryItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventoryItem(arg0);
            return result;
        }
    }
    async deletePettyCash(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePettyCash(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePettyCash(arg0);
            return result;
        }
    }
    async getAllChallans(): Promise<Array<Challan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChallans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChallans();
            return result;
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return result;
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return result;
        }
    }
    async getAllPettyCashRecords(): Promise<Array<PettyCash>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPettyCashRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPettyCashRecords();
            return result;
        }
    }
    async getAllPettyCashRecordsWithAttachments(): Promise<Array<PettyCashWithAttachments>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPettyCashRecordsWithAttachments();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPettyCashRecordsWithAttachments();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttachmentsForPettyCashRecord(arg0: bigint): Promise<Array<PettyCashAttachment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttachmentsForPettyCashRecord(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttachmentsForPettyCashRecord(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuildMetadata(): Promise<BuildMetadata> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuildMetadata();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuildMetadata();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChallansByClient(arg0: string): Promise<Array<Challan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallansByClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallansByClient(arg0);
            return result;
        }
    }
    async getChallansByDateRange(arg0: bigint, arg1: bigint): Promise<Array<Challan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallansByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallansByDateRange(arg0, arg1);
            return result;
        }
    }
    async getInventory(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventory();
            return result;
        }
    }
    async getPaymentsByClient(arg0: string): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByClient(arg0);
            return result;
        }
    }
    async getPaymentsByDateRange(arg0: bigint, arg1: bigint): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByDateRange(arg0, arg1);
            return result;
        }
    }
    async getPettyCashByDateRange(arg0: bigint, arg1: bigint): Promise<Array<PettyCash>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPettyCashByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPettyCashByDateRange(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async healthCheck(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.healthCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthCheck();
            return result;
        }
    }
    async isAdminOrBootstrapAdminExternal(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminOrBootstrapAdminExternal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminOrBootstrapAdminExternal();
            return result;
        }
    }
    async isBootstrapAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isBootstrapAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isBootstrapAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async markChallanReturned(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markChallanReturned(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markChallanReturned(arg0);
            return result;
        }
    }
    async removeAttachmentFromPettyCashRecord(arg0: bigint, arg1: string): Promise<Array<PettyCashAttachment>> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAttachmentFromPettyCashRecord(arg0, arg1);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAttachmentFromPettyCashRecord(arg0, arg1);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async revertChallanToActive(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revertChallanToActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revertChallanToActive(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateChallan(arg0: string, arg1: string, arg2: string, arg3: Array<ChallanItem>, arg4: number, arg5: number, arg6: bigint, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChallan(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChallan(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateChallanRentDates(arg0: Array<Challan>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChallanRentDates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChallanRentDates(arg0);
            return result;
        }
    }
    async updateInventoryItem(arg0: string, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePettyCash(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Array<PettyCashCategory>, arg10: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePettyCash(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePettyCash(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_BecomeAdminResponse_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BecomeAdminResponse): BecomeAdminResponse {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_BulkChallanCreateResult_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BulkChallanCreateResult): BulkChallanCreateResult {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ClientBulkCreateResult_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientBulkCreateResult): ClientBulkCreateResult {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InventoryBulkCreateResult_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryBulkCreateResult): InventoryBulkCreateResult {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentBulkCreateResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentBulkCreateResult): PaymentBulkCreateResult {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_PettyCashAttachment_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PettyCashAttachment): Promise<PettyCashAttachment> {
    return await from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PettyCashBulkCreateResult_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PettyCashBulkCreateResult): PettyCashBulkCreateResult {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_PettyCashWithAttachments_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PettyCashWithAttachments): Promise<PettyCashWithAttachments> {
    return await from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PettyCash]): PettyCash | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Client]): Client | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InventoryItem]): InventoryItem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Challan]): Challan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: _ExternalBlob;
}): Promise<{
    id: string;
    blob: ExternalBlob;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.blob)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isAlreadyAdmin: boolean;
    error: [] | [string];
    success: boolean;
}): {
    isAlreadyAdmin: boolean;
    error?: string;
    success: boolean;
} {
    return {
        isAlreadyAdmin: value.isAlreadyAdmin,
        error: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    created: [] | [_Payment];
    error: [] | [string];
    success: boolean;
}): {
    id: string;
    created?: Payment;
    error?: string;
    success: boolean;
} {
    return {
        id: value.id,
        created: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.created)),
        error: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: [] | [_PettyCash];
    date: bigint;
    error: [] | [string];
    success: boolean;
}): {
    created?: PettyCash;
    date: bigint;
    error?: string;
    success: boolean;
} {
    return {
        created: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.created)),
        date: value.date,
        error: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: [] | [_Client];
    name: string;
    error: [] | [string];
    success: boolean;
}): {
    created?: Client;
    name: string;
    error?: string;
    success: boolean;
} {
    return {
        created: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.created)),
        name: value.name,
        error: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: [] | [_InventoryItem];
    name: string;
    error: [] | [string];
    success: boolean;
}): {
    created?: InventoryItem;
    name: string;
    error?: string;
    success: boolean;
} {
    return {
        created: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.created)),
        name: value.name,
        error: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    created: [] | [_Challan];
    error: [] | [string];
    success: boolean;
}): {
    id: string;
    created?: Challan;
    error?: string;
    success: boolean;
} {
    return {
        id: value.id,
        created: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.created)),
        error: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
async function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    attachments: Array<_PettyCashAttachment>;
    pettyCash: _PettyCash;
}): Promise<{
    attachments: Array<PettyCashAttachment>;
    pettyCash: PettyCash;
}> {
    return {
        attachments: await from_candid_vec_n11(_uploadFile, _downloadFile, value.attachments),
        pettyCash: value.pettyCash
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n49(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
async function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PettyCashAttachment>): Promise<Array<PettyCashAttachment>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PettyCashAttachment_n12(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentBulkCreateResult>): Array<PaymentBulkCreateResult> {
    return value.map((x)=>from_candid_PaymentBulkCreateResult_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PettyCashBulkCreateResult>): Array<PettyCashBulkCreateResult> {
    return value.map((x)=>from_candid_PettyCashBulkCreateResult_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClientBulkCreateResult>): Array<ClientBulkCreateResult> {
    return value.map((x)=>from_candid_ClientBulkCreateResult_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryBulkCreateResult>): Array<InventoryBulkCreateResult> {
    return value.map((x)=>from_candid_InventoryBulkCreateResult_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BulkChallanCreateResult>): Array<BulkChallanCreateResult> {
    return value.map((x)=>from_candid_BulkChallanCreateResult_n37(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PettyCashWithAttachments>): Promise<Array<PettyCashWithAttachments>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PettyCashWithAttachments_n41(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n47(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_PettyCashAttachment_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PettyCashAttachment): Promise<_PettyCashAttachment> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: ExternalBlob;
}): Promise<{
    id: string;
    blob: _ExternalBlob;
}> {
    return {
        id: value.id,
        blob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.blob)
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
